# Imports

In [1]:
import pandas as pd
import numpy as np
import psycopg2
import pandas as pd
import pandas.io.sql as psql
from sqlalchemy import create_engine, text

# Conexão com ElephantSQL

In [2]:
#Preencher com os parametros do seu database do elephantsql
db_params = {
    'host': 'silly.db.elephantsql.com',
    'database': 'gpktqmyr',
    'user': 'gpktqmyr',
    'password': '7fteS2MDOlVYl1An-aQASuGjeADCX4hV'
}

In [3]:
#Criando conexão
conn = psycopg2.connect(
    host=db_params['host'],
    database=db_params['database'],
    user=db_params['user'],
    password=db_params['password']
)

#Criação de Tabela

In [4]:
# Create a cursor object
cur = conn.cursor()

# Set automatic commit to be true, so that each action is committed without having to call conn.committ() after each command
conn.set_session(autocommit=True)

In [7]:
# Criar tabela
cur.execute('''
    DROP TABLE transaction;

''')

UndefinedTable: table "transaction" does not exist

In [6]:
#Fechando conexão, boa prática
cur.close()
conn.close()

# Inserção de Dados

In [11]:
#Definindo a engine do banco de dados
engine = create_engine(f'postgresql://{db_params["user"]}:{db_params["password"]}@{db_params["host"]}/{db_params["database"]}')

file = 'fraudValidate.csv'

In [12]:
# Lendo os dados
df = pd.read_csv("C:\Users\T-GAMER\Downloads\test\notebooks\fraudValidate.csv")

,Unnamed: 0.1,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:04:42,3.007469e+13,fraud_Rowe-Vandervort,grocery_net,44.54,Kelsey,Richards,F,889 Sarah Station Suite 624,...,37.9931,-100.9893,2691,Arboriculturist,1993-08-16,83ec1cc84142af6e2acf10c44949e720,1325376282,37.162705,-100.153370,0
1,1,2019-01-01 00:05:18,4.922711e+15,fraud_Herzog Ltd,misc_pos,4.27,Heather,Chase,F,6888 Hicks Stream Suite 954,...,40.3359,-79.6607,1472,Public affairs consultant,1941-03-07,fc28024ce480f8ef21a32d64c93a29f5,1325376318,40.351813,-79.958146,0
2,2,2019-01-01 00:06:01,2.720830e+15,"fraud_Schoen, Kuphal and Nitzsche",grocery_pos,198.39,Melissa,Aguilar,F,21326 Taylor Squares Suite 708,...,36.5220,-87.3490,151785,Pathologist,1974-03-28,3b9014ea8fb80bd65de0b1463b00b00e,1325376361,37.179198,-87.485381,0
3,3,NaN,4.642895e+12,fraud_Rutherford-Mertz,grocery_pos,24.74,Eddie,Mendez,M,1831 Faith View Suite 653,...,40.7491,-95.0380,7297,IT trainer,1990-07-13,d71c95ab6b7356dd74389d41df429c87,1325376383,40.275891,-96.011548,0
4,4,2019-01-01 00:11:14,2.348245e+15,"fraud_Konopelski, Schneider and Hartmann",food_dining,63.07,Justin,Gay,M,268 Hayes Rue Suite 811,...,42.1767,-79.9416,-999999,Event organiser,1946-02-02,8500f3d459047eac8443307b1e8296e5,1325376674,41.430274,-79.492553,0

In [14]:
df.to_sql('transactions', engine, if_exists='replace', index=False)

351

# SQL

## Exemplos

In [5]:
# Create a cursor object
cur = conn.cursor()

# Set automatic commit to be true, so that each action is committed without having to call conn.committ() after each command
conn.set_session(autocommit=True)

In [6]:
# Verificando quantas linhas tenho na minha tabela, quantidade de links de
#phishing e o percentual total de links de phishing na minha tabela
query = '''
SELECT
  COUNT(*) AS QTD_LINHAS,
  SUM(PHISHING) AS QTD_LINKS_PHISHING,
  AVG(PHISHING) AS PERC_LINKS_PHISHING
FROM PHISHING_DATA
'''

In [ ]:
df_result = psql.read_sql(query, conn)

<ipython-input-24-669134710368>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_result = psql.read_sql(query, conn)

In [ ]:
df_result

   qtd_linhas  qtd_links_phishing  perc_links_phishing
0      100077             35575.0             0.362733

In [ ]:
# Verificando quantidade de phishings e percentual baseado no tamanho da url
query = '''
SELECT
  URL_LENGTH,
  COUNT(*) AS QTD_LINHAS,
  SUM(PHISHING) AS QTD_PHISHING,
  AVG(PHISHING) AS PERC_PHISHING
FROM PHISHING_DATA
GROUP BY URL_LENGTH
'''

In [ ]:
df_result = psql.read_sql(query, conn)
df_result.head(10)

<ipython-input-33-2b4e420b2406>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_result = psql.read_sql(query, conn)

   url_length  qtd_linhas  qtd_phishing  perc_phishing
0         938           1           1.0       1.000000
1         184           6           6.0       1.000000
2          87         136         108.0       0.812030
3         477           2           2.0       1.000000
4         273           9           9.0       1.000000
5         550           1           0.0       0.000000
6          51         627         503.0       0.820555
7         272           9           8.0       1.000000
8          70         331         255.0       0.789474
9         190          18          18.0       1.000000

In [ ]:
# Agrupando o tamanho das url em pequenas, médias e grandes, e verificando as métricas
query = '''
SELECT
  CASE WHEN URL_LENGTH < 100 then 'PEQUENA'
       WHEN URL_LENGTH < 400 then 'MEDIA'
      ELSE 'GRANDE'
  END AS TAMANHO_URL,
  COUNT(*) AS QTD_LINHAS,
  SUM(PHISHING) AS QTD_PHISHING,
  AVG(PHISHING) AS PERC_PHISHING
FROM PHISHING_DATA
GROUP BY CASE WHEN URL_LENGTH < 100 then 'PEQUENA'
              WHEN URL_LENGTH < 400 then 'MEDIA'
              ELSE 'GRANDE'
      END
ORDER BY COUNT(*)
'''

In [ ]:
df_result = psql.read_sql(query, conn)
df_result

<ipython-input-38-7aad1cef14bc>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_result = psql.read_sql(query, conn)

  tamanho_url  qtd_linhas  qtd_phishing  perc_phishing
0      GRANDE         149         141.0       0.959184
1       MEDIA        5878        5288.0       0.920613
2     PEQUENA       94050       30146.0       0.327020

## Pra vocês praticarem

Links de apoio: https://learnsql.com/blog/sql-basics-cheat-sheet/

## Dataset de Fraude

Utilize somente SQL para responder as perguntas abaixo


*   Qual o total de transações, total de transações fraudulentas e percentual de transações fraudulentas tem na sua tabela?
*   Qual os top 10 estabelecimentos com maior concentração de transações fraudulentas?
*   Em quais cidades estão concentrados 90% de todas as fraudes da sua tabela?
*   Qual número de conta tem mais transações fraudulentas? E qual número de conta tem a maior soma de valor de fraude?
*   Qual o total de transações, total de transações fraudulentas e percentual de transações fraudulentas por horários do dia?

1 - 270351 transações no total. 1524 são fraudes. 0.5637116193393034 %


2 -	
        merchant	                total
0	fraud_Kiehn-Emmerich	15.0
1	fraud_Kilback LLC	12.0
2	fraud_Kozey-Boehm	12.0
3	fraud_Heathcote LLC	12.0
4	fraud_Cole PLC	11.0
5	fraud_Baumbach, Feeney and Morar	10.0
6	fraud_Koepp-Parker	10.0
7	fraud_Greenholt, O'Hara and Balistreri	10.0
8	fraud_Gleason-Macejkovic	10.0
9	fraud_Goodwin-Nitzsche	10.0


3-

In [6]:
df = pd.read_csv("fraudValidate.csv")

In [309]:
df.head()

,Unnamed: 0.1,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,6,2019-01-01 00:04:42,3.007469e+13,fraud_Rowe-Vandervort,grocery_net,44.54,Kelsey,Richards,F,...,37.9931,-100.9893,2691,Arboriculturist,1993-08-16,83ec1cc84142af6e2acf10c44949e720,1325376282,37.162705,-100.153370,0
1,1,8,2019-01-01 00:05:18,4.922711e+15,fraud_Herzog Ltd,misc_pos,4.27,Heather,Chase,F,...,40.3359,-79.6607,1472,Public affairs consultant,1941-03-07,fc28024ce480f8ef21a32d64c93a29f5,1325376318,40.351813,-79.958146,0
2,2,9,2019-01-01 00:06:01,2.720830e+15,"fraud_Schoen, Kuphal and Nitzsche",grocery_pos,198.39,Melissa,Aguilar,F,...,36.5220,-87.3490,151785,Pathologist,1974-03-28,3b9014ea8fb80bd65de0b1463b00b00e,1325376361,37.179198,-87.485381,0
3,3,10,NaN,4.642895e+12,fraud_Rutherford-Mertz,grocery_pos,24.74,Eddie,Mendez,M,...,40.7491,-95.0380,7297,IT trainer,1990-07-13,d71c95ab6b7356dd74389d41df429c87,1325376383,40.275891,-96.011548,0
4,4,18,2019-01-01 00:11:14,2.348245e+15,"fraud_Konopelski, Schneider and Hartmann",food_dining,63.07,Justin,Gay,M,...,42.1767,-79.9416,-999999,Event organiser,1946-02-02,8500f3d459047eac8443307b1e8296e5,1325376674,41.430274,-79.492553,0

In [344]:
query = '''
SELECT
  COUNT(IS_FRAUD) as total,
  SUM(IS_FRAUD) as total_fraudes,
  AVG(IS_FRAUD) as media_fraudes

  FROM transactions
  
  


''' 

print((1524/270351) *100)

0.5637116193393034

In [345]:
df_result = psql.read_sql(query, conn)
df_result

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_27480\1607457878.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_result = psql.read_sql(query, conn)

    total  total_fraudes  media_fraudes
0  270351         1524.0       0.005637

In [294]:
query = '''
SELECT
  city,
  SUM(is_fraud) AS totaldefraudes
FROM transactions
WHERE is_fraud = 1
GROUP BY city
ORDER BY SUM(is_fraud) DESC

  



'''

In [180]:
df.head()

,Unnamed: 0.1,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,6,2019-01-01 00:04:42,3.007469e+13,fraud_Rowe-Vandervort,grocery_net,44.54,Kelsey,Richards,F,...,37.9931,-100.9893,2691,Arboriculturist,1993-08-16,83ec1cc84142af6e2acf10c44949e720,1325376282,37.162705,-100.153370,0
1,1,8,2019-01-01 00:05:18,4.922711e+15,fraud_Herzog Ltd,misc_pos,4.27,Heather,Chase,F,...,40.3359,-79.6607,1472,Public affairs consultant,1941-03-07,fc28024ce480f8ef21a32d64c93a29f5,1325376318,40.351813,-79.958146,0
2,2,9,2019-01-01 00:06:01,2.720830e+15,"fraud_Schoen, Kuphal and Nitzsche",grocery_pos,198.39,Melissa,Aguilar,F,...,36.5220,-87.3490,151785,Pathologist,1974-03-28,3b9014ea8fb80bd65de0b1463b00b00e,1325376361,37.179198,-87.485381,0
3,3,10,NaN,4.642895e+12,fraud_Rutherford-Mertz,grocery_pos,24.74,Eddie,Mendez,M,...,40.7491,-95.0380,7297,IT trainer,1990-07-13,d71c95ab6b7356dd74389d41df429c87,1325376383,40.275891,-96.011548,0
4,4,18,2019-01-01 00:11:14,2.348245e+15,"fraud_Konopelski, Schneider and Hartmann",food_dining,63.07,Justin,Gay,M,...,42.1767,-79.9416,-999999,Event organiser,1946-02-02,8500f3d459047eac8443307b1e8296e5,1325376674,41.430274,-79.492553,0

## Dataset de Churn

Utilize somente SQL para responder as perguntas abaixo


*   Qual o total de clientes, total de clientes que realizaram churn e percentual churns tem na sua tabela?
*   Qual os top 2 paises com maior concentração de churn?
*   Em quais paises estão concentrados 90% de todos os clientes que tiveram churn?
*   Qual a idade média e o balanço médio dos clientes que tiveram churn?E dos que não tiveram?
*   Qual o total de clientes, total de churns e percentual de churn para as três faixas de renda a seguir [0-1000); [1000-3500); [3500-infinito)?

In [7]:
df.corr()

ValueError: could not convert string to float: '2019-01-01 00:04:42'